export const templatesData = [
  {
    id: "template-modern",
    name: "Modern",
    nameAr: "الحديث",
    slug: "modern",
    description: "Clean and minimal design perfect for any business",
    descriptionAr: "تصميم نظيف وبسيط مناسب لأي متجر",
    price: 0,
    billingType: "free",
    category: "all",
    thumbnail: "/templates/modern-thumb.png",
    previewUrl: "/preview/modern",
    features: ["Fast Loading", "Mobile Optimized", "RTL Support", "High Conversion"],
    defaultColors: {
      primaryColor: "#0066cc",
      secondaryColor: "#f0f0f0",
    },
    usageCount: 234,
    rating: 4.8,
    reviews: 145,
    isNew: false,
    featured: true,
    componentPath: "free/modern",
  },
  {
    id: "template-bold",
    name: "Bold",
    nameAr: "المميز",
    slug: "bold",
    description: "Eye-catching colors and animations",
    descriptionAr: "ألوان جذابة وحركات أنيقة",
    price: 0,
    billingType: "free",
    category: "all",
    thumbnail: "/templates/bold-thumb.png",
    previewUrl: "/preview/bold",
    features: ["Animated Sections", "Strong Typography", "Mobile First", "Visual Storytelling"],
    defaultColors: {
      primaryColor: "#ef4444",
      secondaryColor: "#fef2f2",
    },
    usageCount: 189,
    rating: 4.7,
    reviews: 112,
    isNew: false,
    featured: true,
    componentPath: "free/bold",
  },
  {
    id: "template-luxury",
    name: "Luxury",
    nameAr: "الفاخر",
    slug: "luxury",
    description: "Premium dark theme with elegant touches",
    descriptionAr: "موضوع مظلم متميز مع لمسات أنيقة",
    price: 20,
    billingType: "monthly",
    category: "premium",
    thumbnail: "/templates/luxury-thumb.png",
    previewUrl: "/preview/luxury",
    features: ["Dark Mode", "Gold Accents", "Advanced Animations", "Wishlist Feature"],
    defaultColors: {
      primaryColor: "#1f2937",
      secondaryColor: "#f59e0b",
    },
    usageCount: 67,
    rating: 4.9,
    reviews: 48,
    isNew: false,
    featured: false,
    componentPath: "paid/luxury",
  },
  {
    id: "template-marketplace",
    name: "Marketplace",
    nameAr: "السوق",
    slug: "marketplace",
    description: "B2B & Wholesale focused template",
    descriptionAr: "قالب متخصص في البيع بالجملة والبيع B2B",
    price: 100,
    billingType: "one-time",
    category: "premium",
    thumbnail: "/templates/marketplace-thumb.png",
    previewUrl: "/preview/marketplace",
    features: ["Category Pages", "Bulk Orders", "Wholesale Pricing", "RFQ Feature"],
    defaultColors: {
      primaryColor: "#0066cc",
      secondaryColor: "#f8fafc",
    },
    usageCount: 42,
    rating: 4.6,
    reviews: 28,
    isNew: true,
    featured: false,
    componentPath: "paid/marketplace",
  },
] as const;

export type TemplateSeed = (typeof templatesData)[number];
